structure(list(url = "https://api.open-meteo.com/v1/forecast?latitude=-12.46113&longitude=130.84184&current_weather=TRUE&timezone=auto&temperature_unit=asdfsfd&windspeed_unit=asdfsd", 
    status_code = 400L, headers = structure(list(date = "Sat, 05 Aug 2023 08:15:44 GMT", 
        `content-type` = "application/json; charset=utf-8", `content-length` = "102", 
        `content-encoding` = "deflate"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 400L, version = "HTTP/2", 
        headers = structure(list(date = "Sat, 05 Aug 2023 08:15:44 GMT", 
            `content-type` = "application/json; charset=utf-8", 
            `content-length` = "102", `content-encoding` = "deflate"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"reason\":\"Cannot initialize TemperatureUnit from invalid String value asdfsfd for key temperature_unit\",\"error\":true}"), 
    date = structure(1691223344, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.3e-05, 
    connect = 0.307425, pretransfer = 0.864824, starttransfer = 1.140693, 
    total = 1.140766)), class = "response")
